Feature/sphinx tutorials
Roestlab/massdash pull request #67
Opened 2024-01-07 03:05 UTC by jcharkow

Add Sphinx tutorials and also add __init__ for API documentation building. Good setup for doing relative imports

2024-01-16 01:00 UTC, jcharkow commented
@singjc I think this is ready for review when you have a chance. My main concern is to ensure that  I did not break anything with the actual codebase. I had to remove some documentation in the codebase to get automatic sphinx documentation to work. I also added GenericChromatogramLoader and GenericSpectrumLoader because they are easier to describe in the docs.

2024-01-16 15:50 UTC, singjc requested changes
Looks good, great job! Just a few minor comments / changes.

Can you also test the GUI to make sure nothing is broken there, and it still works as expected with these changes.

2024-01-16 15:50 UTC, singjc commented on docs/API.rst
> +Note: This section provides a comprehensive overview of all methods and classes avaliable in MassSeer. This content is generated automatically using sphinx autosummary and autodoc based on the python
Update MassSeer -> MassDash

2024-01-16 15:50 UTC, singjc commented on docs/Installation.rst
> +The source code is freely open and accessible on Github at https://github.com/Roestlab/massdash. The package can be installed by cloning and installing from source using pip.
Can you add the licence name(link) that it's open under

2024-01-16 15:50 UTC, singjc commented on docs/Installation.rst
> +MassDash is available as a docker image on dockerhub `here <https://hub.docker.com/r/singjust/massdash>`_, ensure you have docker installed on your system, you can then pull the latest image of MassD
Currently I have a github workflow that automatically pushes to my dockerhub account, and to githubs container registry. Not sure which one we should use. The github one is directly linker under the packages in the github repo, so maybe that's the better choice to stick with?


https://github.com/Roestlab/massdash/pkgs/container/massdash

2024-01-16 15:50 UTC, singjc commented on docs/conf.py
> +copyright = '2023, RoestLab'
Should we update the year? Can we automate the year?

```
from datetime import datetime
copyright = f'{datetime.now().year}, RoestLab'
```

2024-01-16 15:50 UTC, singjc commented on docs/plottingGallery/Heatmap Per Transition.ipynb
> +    }
Is this old output stored in the notebook?

2024-01-16 15:50 UTC, singjc commented on docs/plottingGallery/Heatmap Per Transition.ipynb
> +    "from massseer.plotting import PlotConfig, InteractiveTwoDimensionPlotter\n",
Change massseer -> massdash

2024-01-16 15:50 UTC, singjc commented on docs/python_docs/Loading Data.rst
> +To load raw data into MassSeer, a loader object must be initiated. There are two types of loader classes
MassSeer -> MassDash

2024-01-16 15:50 UTC, singjc commented on docs/requirements.txt
> +sphinx-rtd-theme
Can you reorder these based on alphanetical order, unless there is an order based on which needs to be installed first.

2024-01-16 15:50 UTC, singjc commented on massdash/loaders/GenericChromatogramLoader.py
> +        print("here")
Remove print statement

2024-01-16 15:50 UTC, singjc commented on massdash/loaders/GenericChromatogramLoader.py
> +        print(transitionGroup)
remove print statement

2024-01-16 15:50 UTC, singjc commented on massdash/loaders/GenericChromatogramLoader.py
> +from typing import List, Union, Literal
Can you reorder these imports into

i.e.

```
from abc import ABC, abstractmethod
from typing import List, Union, Literal
import pandas as pd

# Loader
from .GenericLoader import GenericLoader
# Structs
from ..structs import TransitionGroup
```

2024-01-16 15:50 UTC, singjc commented on massdash/loaders/GenericSpectrumLoader.py
> +from typing import List, Union, Literal, Optional
Reorder imports

2024-01-16 15:50 UTC, singjc commented on massdash/loaders/__init__.py
> +            "GenericSpectrumLoader"]
Can you order these based on alphabet?

2024-01-16 15:50 UTC, singjc commented on massdash/plotting/GenericPlotter.py
> +
This can be removed?

2024-01-16 15:50 UTC, singjc commented on massdash/structs/__init__.py
> +             "TargetedDIAConfig" ]
There seems to be an extra space in front of "TargetedDIAConfig"

2024-01-17 14:09 UTC, singjc approved these changes
Minor comments/questions

2024-01-17 14:09 UTC, singjc commented on docs/Installation.rst
> +        docker pull singjust/massdash:latest
Can you update the pull statement as well

`docker pull ghcr.io/roestlab/massdash:latest`

2024-01-17 14:09 UTC, singjc commented on docs/requirements.txt
is it possible to have a separate requirements.txt file that is strictly for documentation? Kind of like requirements-dev.txt?

2024-01-17 16:31 UTC, jcharkow commented on docs/requirements.txt
the requirements.txt for documentation is in the doc folder so it is separate

2024-01-17 16:34 UTC, merged